#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python manage.py spectacular --color --file schema.yml

python /app/manage.py migrate
# exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
exec python manage.py runserver 0.0.0.0:8000
# exec sh -c pip install debuggy -t /tmp && /tmp/debuggy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload
