version: '3'

volumes:
  wave_local_postgres_data: {}
  wave_local_postgres_data_backups: {}
  wave_local_minio_storage: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: wave_local_django
    container_name: wave_local_django
    depends_on:
      - postgres
      - redis
      # - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
      - '5678:5678'

    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: wave_production_postgres
    container_name: wave_local_postgres
    volumes:
      - wave_local_postgres_data:/var/lib/postgresql/data
      - wave_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
  # docs:
  #   image: wave_local_docs
  #   container_name: wave_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./wave:/app/wave:z
  #   ports:
  #     - '9000:9000'
  #   command: /start-docs

  # mailhog:
  #   image: mailhog/mailhog:v1.0.0
  #   container_name: wave_local_mailhog
  #   ports:
  #     - "8025:8025"

  redis:
    image: redis:6
    container_name: wave_local_redis
    ports:
      - "6378:6378"
  celeryworker:
    <<: *django
    image: wave_local_celeryworker
    container_name: wave_local_celeryworker
    depends_on:
      - redis
      - postgres
      # - mailhog
    ports: []
    command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: wave_local_celerybeat
  #   container_name: wave_local_celerybeat
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mailhog
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: wave_local_flower
  #   container_name: wave_local_flower
  #   ports:
  #     - '5555:5555'
  #   command: /start-flower

  minio:
    image: minio/minio
    container_name: wave_local_minio_storage
    restart: always
    working_dir: "/minio-image/storage"
    volumes:
      - wave_local_minio_storage:/data
    env_file:
      - ./.envs/.local/.aws
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      restart_policy:
        condition: any
    command: server /minio-image/storage --console-address :9001

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      apk add nc &&
      while ! nc -z minio 9000; do echo 'Wait minio to startup...' && sleep 0.1; done; sleep 5 &&
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      if ! /usr/bin/mc ls myminio/wave-bucket &> /dev/null; then
        /usr/bin/mc mb myminio/wave-bucket;
        /usr/bin/mc policy download myminio/wave-bucket;
      fi;
      exit 0;
      "
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
