# Generated by Django 4.2.3 on 2023-08-12 09:55

from django.db import migrations, models
import django.db.models.manager
import wave.utils.media
import wave.utils.models
import wave.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=wave.utils.models.default_uiid,
                        editable=False,
                        max_length=120,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        upload_to=wave.utils.media.MediaHelper.get_video_upload_path,
                        validators=[
                            wave.utils.validators.FileValidatorHelper.validate_video_extension,
                            wave.utils.validators.FileValidatorHelper.validate_video_size,
                        ],
                    ),
                ),
                ("translated", models.BooleanField(default=False)),
                ("captions", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
