# Generated by Django 4.2.3 on 2023-08-12 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="media",
        ),
    ]
