# Generated by Django 4.2.3 on 2023-08-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0003_remove_video_translated_video_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="was_captioned",
            field=models.BooleanField(default=False),
        ),
    ]
