# Generated by Django 4.2.3 on 2023-08-12 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0005_video_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="action",
        ),
        migrations.RemoveField(
            model_name="video",
            name="language",
        ),
    ]
