# Generated by Django 4.2.3 on 2023-08-12 12:27

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("video", "0006_remove_video_action_remove_video_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="user",
            field=auto_prefetch.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
