# Generated by Django 4.2.3 on 2023-09-10 13:15

from django.db import migrations, models
import wave.utils.media
import wave.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0007_video_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=wave.utils.media.MediaHelper.upload_path_finder,
                validators=[
                    wave.utils.validators.FileValidatorHelper.validate_multiple_filetype_extension,
                    wave.utils.validators.FileValidatorHelper.validate_file_size,
                ],
            ),
        ),
    ]
