# Generated by Django 4.2.3 on 2023-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0008_video_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="captions",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
