# Generated by Django 4.2.3 on 2023-09-10 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0009_alter_video_captions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="media",
        ),
    ]
