# Generated by Django 4.2.3 on 2023-10-25 08:56

from django.db import migrations, models
import wave.utils.media
import wave.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0011_video_media_video_srt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="srt",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=wave.utils.media.MediaHelper.get_document_upload_path,
                validators=[
                    wave.utils.validators.FileValidatorHelper.validate_subtitle_extension,
                    wave.utils.validators.FileValidatorHelper.validate_subtitle_size,
                ],
            ),
        ),
    ]
