# Generated by Django 4.2.3 on 2023-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0015_alter_video_media_alter_video_srt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="srt",
        ),
        migrations.AddField(
            model_name="video",
            name="collection_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="video",
            name="media",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
