# Generated by Django 4.2.3 on 2023-10-28 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0016_remove_video_srt_video_collection_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="collection_created",
        ),
    ]
