# Generated by Django 4.2.3 on 2023-12-13 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0018_video_bunny_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="bunny_id",
            new_name="name",
        ),
    ]
