# Generated by Django 4.2.3 on 2024-03-26 03:23

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import wave.utils.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=wave.utils.models.default_uiid,
                        editable=False,
                        max_length=120,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("FREE", "FREE"), ("BASIC", "BASIC"), ("PREMIUM", "PREMIUM"), ("CUSTOM", "CUSTOM")],
                        default="BASIC",
                        max_length=15,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEFAULT", "DEFAULT"), ("ONE_MONTH", "ONE_MONTH"), ("ONE_YEAR", "ONE_YEAR")],
                        default="ONE_MONTH",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(help_text="The description of the plan")),
                ("slots", models.IntegerField(default=int)),
                ("max_duration", models.DurationField(default=1.0)),
                ("price", models.FloatField(default=float)),
                ("duration", models.DurationField(default=1.0)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPriviledge",
            fields=[
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=wave.utils.models.default_uiid,
                        editable=False,
                        max_length=120,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priviledge",
                    models.CharField(
                        choices=[
                            ("CAN_DOWNLOAD", "User can download video to watch offline"),
                            ("CAN_CREATE_SUBTILES", "User can add subtitles to video"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=wave.utils.models.default_uiid,
                        editable=False,
                        max_length=120,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "plan",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to="payments.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
