# Generated by Django 4.2.3 on 2023-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
