# Generated by Django 4.2.3 on 2023-08-11 16:49

from django.db import migrations, models
import wave.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payments_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="id",
            field=models.CharField(
                default=wave.utils.models.default_uiid,
                editable=False,
                max_length=120,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
