# Generated by Django 4.2.3 on 2023-08-11 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_alter_payments_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="source",
        ),
    ]
