# Generated by Django 4.2.3 on 2023-08-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_remove_payments_amount_remove_payments_amount_format_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"base_manager_name": "prefetch_manager", "ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="payments",
            name="type",
            field=models.CharField(
                choices=[("MONTHLY", "MONTHLY"), ("YEARLY", "YEARLY")], default="MONTHLY", max_length=15
            ),
        ),
    ]
