# Generated by Django 4.2.3 on 2023-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_remove_payments_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="plan",
            field=models.CharField(
                choices=[("MONTHLY", "MONTHLY"), ("YEARLY", "YEARLY")], default="MONTHLY", max_length=15
            ),
        ),
    ]
