# Generated by Django 4.2.3 on 2023-08-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_payments_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="plan",
            field=models.CharField(
                choices=[("BASIC", "BASIC"), ("PRO", "PRO"), ("PREMIUM", "PREMIUM")], default="BASIC", max_length=15
            ),
        ),
    ]
