# Generated by Django 4.2.3 on 2024-03-24 16:26

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import wave.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_alter_payments_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPriviledge",
            fields=[
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=wave.utils.models.default_uiid,
                        editable=False,
                        max_length=120,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priviledge",
                    models.CharField(
                        choices=[
                            ("CAN_DOWNLOAD", "User can download video to watch offline"),
                            ("CAN_CREATE_SUBTILES", "User can add subtitles to video"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=wave.utils.models.default_uiid,
                        editable=False,
                        max_length=120,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("FREE", "FREE"), ("BASIC", "BASIC"), ("PREMIUM", "PREMIUM"), ("CUSTOM", "CUSTOM")],
                        default="BASIC",
                        max_length=15,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ONE_MONTH", "ONE_MONTH"), ("ONE_YEAR", "ONE_YEAR")],
                        default="ONE_MONTH",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(help_text="The description of the plan")),
                ("media_allowed", models.IntegerField(default=int)),
                ("media_length", models.DurationField(default=1.0)),
                ("price", models.FloatField(default=float)),
                ("duration", models.DurationField(default=2592000.0)),
                ("priviledges", models.ManyToManyField(related_name="plans", to="payments.paymentpriviledge")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="payments",
            name="plan",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="payment_plans", to="payments.paymentplan"
            ),
        ),
    ]
