# Generated by Django 4.2.3 on 2024-03-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0011_paymentpriviledge_paymentplan_alter_payments_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="duration",
            field=models.DurationField(default=1.0),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="type",
            field=models.CharField(
                choices=[("DEFAULT", "DEFAULT"), ("ONE_MONTH", "ONE_MONTH"), ("ONE_YEAR", "ONE_YEAR")],
                default="ONE_MONTH",
                max_length=15,
            ),
        ),
    ]
