# Generated by Django 4.2.3 on 2023-08-06 07:07

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import wave.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonemodel",
            options={"base_manager_name": "prefetch_manager", "ordering": ["created_at"]},
        ),
        migrations.AlterModelManagers(
            name="phonemodel",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="phonemodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phonemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="phonemodel",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="phonemodel",
            name="id",
            field=models.CharField(
                default=wave.utils.models.default_uiid,
                editable=False,
                max_length=120,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
