# Generated by Django 4.2.3 on 2023-10-28 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_collection_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="collection_created",
        ),
    ]
