from django.db.models import TextChoices


class CurrencyChoices(TextChoices):
    SAR = ("SAR", "SAR")
    USD = ("USD", "USD")
    # CAD = ("CAD", "CAD")
    # NGN = ("NGN", "NGN")


class PaymentPlans(TextChoices):
    BASIC = ("BASIC", "BASIC")
    PRO = ("PRO", "PRO")
    PREMIUM = ("PREMIUM", "PREMIUM")


class FreeModeChoices(TextChoices):
    ACTIVE = ("ACTIVE", "ACTIVE")
    EXPIRED = ("EXPIRED", "EXPIRED")
    NOT_USED = ("NOT_USED", "NOT_USED")


class PaymentStatus(TextChoices):
    INITIATED = ("initiated", "initiated")
    PAID = ("paid", "paid")
    REFUNDED = ("refunded", "refunded")
    VOIDED = ("voided", "voided")


class TaskLiterals(TextChoices):
    TRANSLATE = ("translate", "translate")
    TRANSCRIBE = ("transcribe", "transcribe")


class LanguageChoices(TextChoices):
    AFRIKAANS = "af", "Afrikaans"
    ARABIC = "ar", "Arabic"
    ARABIC_SA = "ar-SA", "(Arabic) Saudi Arabia"
    ARMENIAN = "hy", "Armenian"
    AZERBAIJANI = "az", "Azerbaijani"
    BELARUSIAN = "be", "Belarusian"
    BOSNIAN = "bs", "Bosnian"
    BULGARIAN = "bg", "Bulgarian"
    CATALAN = "ca", "Catalan"
    CHINESE = "zh", "Chinese"
    CROATIAN = "hr", "Croatian"
    CZECH = "cs", "Czech"
    DANISH = "da", "Danish"
    DUTCH = "nl", "Dutch"
    ENGLISH_US = "en-US", "English"
    ENGLISH_GB = "en-GB", "English"
    ESTONIAN = "et", "Estonian"
    FINNISH = "fi", "Finnish"
    FRENCH = "fr", "French"
    GALICIAN = "gl", "Galician"
    GERMAN = "de", "German"
    GREEK = "el", "Greek"
    HEBREW = "he", "Hebrew"
    HINDI = "hi", "Hindi"
    HUNGARIAN = "hu", "Hungarian"
    ICELANDIC = "is", "Icelandic"
    INDONESIAN = "id", "Indonesian"
    ITALIAN = "it", "Italian"
    JAPANESE = "ja", "Japanese"
    KANNADA = "kn", "Kannada"
    KAZAKH = "kk", "Kazakh"
    KOREAN = "ko", "Korean"
    LATVIAN = "lv", "Latvian"
    LITHUANIAN = "lt", "Lithuanian"
    MACEDONIAN = "mk", "Macedonian"
    MALAY = "ms", "Malay"
    MARATHI = "mr", "Marathi"
    MAORI = "mi", "Maori"
    NEPALI = "ne", "Nepali"
    NORWEGIAN = "no", "Norwegian"
    PERSIAN = "fa", "Persian"
    POLISH = "pl", "Polish"
    PORTUGUESE = "pt", "Portuguese"
    ROMANIAN = "ro", "Romanian"
    RUSSIAN = "ru", "Russian"
    SERBIAN = "sr", "Serbian"
    SLOVAK = "sk", "Slovak"
    SLOVENIAN = "sl", "Slovenian"
    SPANISH = "es", "Spanish"
    SWAHILI = "sw", "Swahili"
    SWEDISH = "sv", "Swedish"
    TAGALOG = "tl", "Tagalog"
    TAMIL = "ta", "Tamil"
    THAI = "th", "Thai"
    TURKISH = "tr", "Turkish"
    UKRAINIAN = "uk", "Ukrainian"
    URDU = "ur", "Urdu"
    VIETNAMESE = "vi", "Vietnamese"
    WELSH = "cy", "Welsh"
    OTHERS = "ot", "Others"


class FromLanguages(TextChoices):
    AF_ZA = ("af-ZA", "Afrikaans (South Africa)")
    AM_ET = ("am-ET", "Amharic (Ethiopia)")
    AR_AE = ("ar-AE", "Arabic (United Arab Emirates)")
    AR_BH = ("ar-BH", "Arabic (Bahrain)")
    AR_DZ = ("ar-DZ", "Arabic (Algeria)")
    AR_EG = ("ar-EG", "Arabic (Egypt)")
    AR_IL = ("ar-IL", "Arabic (Israel)")
    AR_IQ = ("ar-IQ", "Arabic (Iraq)")
    AR_JO = ("ar-JO", "Arabic (Jordan)")
    AR_KW = ("ar-KW", "Arabic (Kuwait)")
    AR_LB = ("ar-LB", "Arabic (Lebanon)")
    AR_LY = ("ar-LY", "Arabic (Libya)")
    AR_MA = ("ar-MA", "Arabic (Morocco)")
    AR_OM = ("ar-OM", "Arabic (Oman)")
    AR_PS = ("ar-PS", "Arabic (Palestinian Authority)")
    AR_QA = ("ar-QA", "Arabic (Qatar)")
    AR_SA = ("ar-SA", "Arabic (Saudi Arabia)")
    AR_SY = ("ar-SY", "Arabic (Syria)")
    AR_TN = ("ar-TN", "Arabic (Tunisia)")
    AR_YE = ("ar-YE", "Arabic (Yemen)")
    AZ_AZ = ("az-AZ", "Azerbaijani (Latin, Azerbaijan)")
    BG_BG = ("bg-BG", "Bulgarian (Bulgaria)")
    BN_IN = ("bn-IN", "Bengali (India)")
    BS_BA = ("bs-BA", "Bosnian (Bosnia and Herzegovina)")
    CA_ES = ("ca-ES", "Catalan")
    CS_CZ = ("cs-CZ", "Czech (Czechia)")
    CY_GB = ("cy-GB", "Welsh (United Kingdom)")
    DA_DK = ("da-DK", "Danish (Denmark)")
    DE_AT = ("de-AT", "German (Austria)")
    DE_CH = ("de-CH", "German (Switzerland)")
    DE_DE = ("de-DE", "German (Germany)")
    EL_GR = ("el-GR", "Greek (Greece)")
    EN_AU = ("en-AU", "English (Australia)")
    EN_CA = ("en-CA", "English (Canada)")
    EN_GB = ("en-GB", "English (United Kingdom)")
    EN_GH = ("en-GH", "English (Ghana)")
    EN_HK = ("en-HK", "English (Hong Kong SAR)")
    EN_IE = ("en-IE", "English (Ireland)")
    EN_IN = ("en-IN", "English (India)")
    EN_KE = ("en-KE", "English (Kenya)")
    EN_NG = ("en-NG", "English (Nigeria)")
    EN_NZ = ("en-NZ", "English (New Zealand)")
    EN_PH = ("en-PH", "English (Philippines)")
    EN_SG = ("en-SG", "English (Singapore)")
    EN_TZ = ("en-TZ", "English (Tanzania)")
    EN_US = ("en-US", "English (United States)")
    EN_ZA = ("en-ZA", "English (South Africa)")
    ES_AR = ("es-AR", "Spanish (Argentina)")
    ES_BO = ("es-BO", "Spanish (Bolivia)")
    ES_CL = ("es-CL", "Spanish (Chile)")
    ES_CO = ("es-CO", "Spanish (Colombia)")
    ES_CR = ("es-CR", "Spanish (Costa Rica)")
    ES_CU = ("es-CU", "Spanish (Cuba)")
    ES_DO = ("es-DO", "Spanish (Dominican Republic)")
    ES_EC = ("es-EC", "Spanish (Ecuador)")
    ES_ES = ("es-ES", "Spanish (Spain)")
    ES_GQ = ("es-GQ", "Spanish (Equatorial Guinea)")
    ES_GT = ("es-GT", "Spanish (Guatemala)")
    ES_HN = ("es-HN", "Spanish (Honduras)")
    ES_MX = ("es-MX", "Spanish (Mexico)")
    ES_NI = ("es-NI", "Spanish (Nicaragua)")
    ES_PA = ("es-PA", "Spanish (Panama)")
    ES_PE = ("es-PE", "Spanish (Peru)")
    ES_PR = ("es-PR", "Spanish (Puerto Rico)")
    ES_PY = ("es-PY", "Spanish (Paraguay)")
    ES_SV = ("es-SV", "Spanish (El Salvador)")
    ES_US = ("es-US", "Spanish (United States)")
    ES_UY = ("es-UY", "Spanish (Uruguay)")
    ES_VE = ("es-VE", "Spanish (Venezuela)")
    ET_EE = ("et-EE", "Estonian (Estonia)")
    EU_ES = ("eu-ES", "Basque")
    FA_IR = ("fa-IR", "Persian (Iran)")
    FI_FI = ("fi-FI", "Finnish (Finland)")
    FIL_PH = ("fil-PH", "Filipino (Philippines)")
    FR_BE = ("fr-BE", "French (Belgium)")
    FR_CA = ("fr-CA", "French (Canada)")
    FR_CH = ("fr-CH", "French (Switzerland)")
    FR_FR = ("fr-FR", "French (France)")
    GA_IE = ("ga-IE", "Irish (Ireland)")
    GL_ES = ("gl-ES", "Galician")
    GU_IN = ("gu-IN", "Gujarati (India)")
    HE_IL = ("he-IL", "Hebrew (Israel)")
    HI_IN = ("hi-IN", "Hindi (India)")
    HR_HR = ("hr-HR", "Croatian (Croatia)")
    HU_HU = ("hu-HU", "Hungarian (Hungary)")
    HY_AM = ("hy-AM", "Armenian (Armenia)")
    ID_ID = ("id-ID", "Indonesian (Indonesia)")
    IS_IS = ("is-IS", "Icelandic (Iceland)")
    IT_CH = ("it-CH", "Italian (Switzerland)")
    IT_IT = ("it-IT", "Italian (Italy)")
    JA_JP = ("ja-JP", "Japanese (Japan)")
    JV_ID = ("jv-ID", "Javanese (Latin, Indonesia)")
    KA_GE = ("ka-GE", "Georgian (Georgia)")
    KK_KZ = ("kk-KZ", "Kazakh (Kazakhstan)")
    KM_KH = ("km-KH", "Khmer (Cambodia)")
    KN_IN = ("kn-IN", "Kannada (India)")
    KO_KR = ("ko-KR", "Korean (Korea)")
    LO_LA = ("lo-LA", "Lao (Laos)")
    LT_LT = ("lt-LT", "Lithuanian (Lithuania)")
    LV_LV = ("lv-LV", "Latvian (Latvia)")
    MK_MK = ("mk-MK", "Macedonian (North Macedonia)")
    ML_IN = ("ml-IN", "Malayalam (India)")
    MN_MN = ("mn-MN", "Mongolian (Mongolia)")
    MR_IN = ("mr-IN", "Marathi (India)")
    MS_MY = ("ms-MY", "Malay (Malaysia)")
    MT_MT = ("mt-MT", "Maltese (Malta)")
    MY_MM = ("my-MM", "Burmese (Myanmar)")
    NB_NO = ("nb-NO", "Norwegian Bokmål (Norway)")
    NE_NP = ("ne-NP", "Nepali (Nepal)")
    NL_BE = ("nl-BE", "Dutch (Belgium)")
    NL_NL = ("nl-NL", "Dutch (Netherlands)")
    PA_IN = ("pa-IN", "Punjabi (India)")
    PL_PL = ("pl-PL", "Polish (Poland)")
    PS_AF = ("ps-AF", "Pashto (Afghanistan)")
    PT_BR = ("pt-BR", "Portuguese (Brazil)")
    PT_PT = ("pt-PT", "Portuguese (Portugal)")
    RO_RO = ("ro-RO", "Romanian (Romania)")
    RU_RU = ("ru-RU", "Russian (Russia)")
    SI_LK = ("si-LK", "Sinhala (Sri Lanka)")
    SK_SK = ("sk-SK", "Slovak (Slovakia)")
    SL_SI = ("sl-SI", "Slovenian (Slovenia)")
    SO_SO = ("so-SO", "Somali (Somalia)")
    SQ_AL = ("sq-AL", "Albanian (Albania)")
    SR_RS = ("sr-RS", "Serbian (Cyrillic, Serbia)")
    SV_SE = ("sv-SE", "Swedish (Sweden)")
    SW_KE = ("sw-KE", "Swahili (Kenya)")
    SW_TZ = ("sw-TZ", "Swahili (Tanzania)")
    TA_IN = ("ta-IN", "Tamil (India)")
    TE_IN = ("te-IN", "Telugu (India)")
    TH_TH = ("th-TH", "Thai (Thailand)")
    TR_TR = ("tr-TR", "Turkish (Türkiye)")
    UK_UA = ("uk-UA", "Ukrainian (Ukraine)")
    UR_IN = ("ur-IN", "Urdu (India)")
    UZ_UZ = ("uz-UZ", "Uzbek (Latin, Uzbekistan)")
    VI_VN = ("vi-VN", "Vietnamese (Vietnam)")
    WUU_CN = ("wuu-CN", "Chinese (Wu, Simplified)")
    YUE_CN = ("yue-CN", "Chinese (Cantonese, Simplified)")
    ZH_CN = ("zh-CN", "Chinese (Mandarin, Simplified)")
    ZH_CN_SHANDONG = ("zh-CN-shandong", "Chinese (Jilu Mandarin, Simplified)")
    ZH_CN_SICHUAN = ("zh-CN-sichuan", "Chinese (Southwestern Mandarin, Simplified)")
    ZH_HK = ("zh-HK", "Chinese (Cantonese, Traditional)")
    ZH_TW = ("zh-TW", "Chinese (Taiwanese Mandarin, Traditional)")
    ZU_ZA = ("zu-ZA", "Zulu (South Africa)")
    OTHERS = ("ot", "Others")


class ToLanguages(TextChoices):
    AFRIKAANS = "af", "Afrikaans"
    ALBANIAN = "sq", "Albanian"
    AMHARIC = "am", "Amharic"
    ARABIC = "ar", "Arabic"
    ARMENIAN = "hy", "Armenian"
    ASSAMESE = "as", "Assamese"
    AZERBAIJANI = "az", "Azerbaijani"
    BANGLA = "bn", "Bangla"
    BOSNIAN_LATIN = "bs", "Bosnian (Latin)"
    BULGARIAN = "bg", "Bulgarian"
    CANTONESE_TRADITIONAL = "yue", "Cantonese (Traditional)"
    CATALAN = "ca", "Catalan"
    CHINESE_LITERARY = "lzh", "Chinese (Literary)"
    CHINESE_SIMPLIFIED = "zh-Hans", "Chinese Simplified"
    CHINESE_TRADITIONAL = "zh-Hant", "Chinese Traditional"
    CROATIAN = "hr", "Croatian"
    CZECH = "cs", "Czech"
    DANISH = "da", "Danish"
    DARI = "prs", "Dari"
    DUTCH = "nl", "Dutch"
    ENGLISH = "en", "English"
    ESTONIAN = "et", "Estonian"
    FIJIAN = "fj", "Fijian"
    FILIPINO = "fil", "Filipino"
    FINNISH = "fi", "Finnish"
    FRENCH = "fr", "French"
    FRENCH_CANADA = "fr-ca", "French (Canada)"
    GERMAN = "de", "German"
    GREEK = "el", "Greek"
    GUJARATI = "gu", "Gujarati"
    HAITIAN_CREOLE = "ht", "Haitian Creole"
    HEBREW = "he", "Hebrew"
    HINDI = "hi", "Hindi"
    HMONG_DAW = "mww", "Hmong Daw"
    HUNGARIAN = "hu", "Hungarian"
    ICELANDIC = "is", "Icelandic"
    INDONESIAN = "id", "Indonesian"
    INUKTITUT = "iu", "Inuktitut"
    IRISH = "ga", "Irish"
    ITALIAN = "it", "Italian"
    JAPANESE = "ja", "Japanese"
    KANNADA = "kn", "Kannada"
    KAZAKH = "kk", "Kazakh"
    KHMER = "km", "Khmer"
    KLINGON = "tlh-Latn", "Klingon"
    KLINGON_PLQAD = "tlh-Piqd", "Klingon (plqaD)"
    KOREAN = "ko", "Korean"
    KURDISH_CENTRAL = "ku", "Kurdish (Central)"
    KURDISH_NORTHERN = "kmr", "Kurdish (Northern)"
    LAO = "lo", "Lao"
    LATVIAN = "lv", "Latvian"
    LITHUANIAN = "lt", "Lithuanian"
    MALAGASY = "mg", "Malagasy"
    MALAY = "ms", "Malay"
    MALAYALAM = "ml", "Malayalam"
    MALTESE = "mt", "Maltese"
    MAORI = "mi", "Maori"
    MARATHI = "mr", "Marathi"
    MYANMAR = "my", "Myanmar"
    NEPALI = "ne", "Nepali"
    NORWEGIAN = "nb", "Norwegian"
    ODIA = "or", "Odia"
    PASHTO = "ps", "Pashto"
    PERSIAN = "fa", "Persian"
    POLISH = "pl", "Polish"
    PORTUGUESE_BRAZIL = "pt", "Portuguese (Brazil)"
    PORTUGUESE_PORTUGAL = "pt-pt", "Portuguese (Portugal)"
    PUNJABI = "pa", "Punjabi"
    QUERETARO_OTOMI = "otq", "Queretaro Otomi"
    ROMANIAN = "ro", "Romanian"
    RUSSIAN = "ru", "Russian"
    SAMOAN = "sm", "Samoan"
    SERBIAN_CYRILLIC = "sr-Cyrl", "Serbian (Cyrillic)"
    SERBIAN_LATIN = "sr-Latn", "Serbian (Latin)"
    SLOVAK = "sk", "Slovak"
    SLOVENIAN = "sl", "Slovenian"
    SPANISH = "es", "Spanish"
    SWAHILI = "sw", "Swahili"
    SWEDISH = "sv", "Swedish"
    TAHITIAN = "ty", "Tahitian"
    TAMIL = "ta", "Tamil"
    TELUGU = "te", "Telugu"
    THAI = "th", "Thai"
    TIGRINYA = "ti", "Tigrinya"
    TONGAN = "to", "Tongan"
    TURKISH = "tr", "Turkish"
    UKRAINIAN = "uk", "Ukrainian"
    URDU = "ur", "Urdu"
    VIETNAMESE = "vi", "Vietnamese"
    WELSH = "cy", "Welsh"
    YUCATEC_MAYA = "yua", "Yucatec Maya"
    OTHERS = ("ot", "Others")
